## Домашнее задание по теме: "Библиотека Pandas"

### Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера.  
Определите, какому фильму было выставлено больше всего оценок 5.0.

In [1]:
# импорт библиотеки pandas
import pandas as pd

In [2]:
# импортируем данные из файлов (только необходимые столбцы)
movies = pd.read_csv('./movies.csv', usecols=['movieId', 'title'])
ratings = pd.read_csv('./ratings.csv', usecols=['movieId', 'rating'])

In [3]:
# проверяем датафреймы
print(movies.head())
print(ratings.head())

   movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)
   movieId  rating
0        1     4.0
1        3     4.0
2        6     4.0
3       47     5.0
4       50     5.0

In [12]:
# фильтрация по оценке 5.0, группировка по movieId с подсчетом количества строк, возврат индекса с максимальным значением
id = ratings[ratings.rating == 5.0].groupby("movieId").count().idxmax()[0]
# фильтрация по полученному id
movies[movies.movieId == id]

     movieId                             title
277      318  Shawshank Redemption, The (1994)

### Задание 2  
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики  
(Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года.  
Не учитывайте в расчетах отрицательные значения quantity.

In [6]:
# импортируем данные из csv
df = pd.read_csv('./power.csv')
# проверяем, что данные загружены
df.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [7]:
# список стран
countries = ['Latvia', 'Lithuania', 'Estonia']
# список категорий
categories = [4, 12, 21]
# период
start_date, end_date = 2005, 2010

# выстраиваем цепочку условий, выбираем столбец quantity и считаем по нему сумму
df[df.country.isin(countries) & df.category.isin(categories) & df.year.between(start_date, end_date) & df.quantity > 0]['quantity'].sum()

240481.0

### Задание 3  
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.

In [13]:
# таблица с продолжительностью светового дня за месяц
daylight = pd.read_html('http://timezone.ru/suncalc.php?tid=213')[4]

In [14]:
# проверка
daylight.head(31)

   Дата  Дата.1 Восход солнца Заход солнца Продолжительность дня Изменение
0    Вc   24.07      04:21:11     20:50:57              16:29:46   - 03:24
1    Пн   25.07      04:22:55     20:49:14              16:26:19   - 03:27
2    Вт   26.07      04:24:40     20:47:29              16:22:49   - 03:30
3    Ср   27.07      04:26:26     20:45:42              16:19:16   - 03:33
4    Чт   28.07      04:28:13     20:43:52              16:15:39   - 03:37
5    Пт   29.07      04:30:02     20:42:00              16:11:58   - 03:41
6    Сб   30.07      04:31:51     20:40:06              16:08:15   - 03:43
7    Вc   31.07      04:33:41     20:38:10              16:04:29   - 03:46
8    Пн    1.08      04:35:31     20:36:12              16:00:41   - 03:48
9    Вт    2.08      04:37:23     20:34:12              15:56:49   - 03:52
10   Ср    3.08      04:39:15     20:32:10              15:52:55   - 03:54
11   Чт    4.08      04:41:07     20:30:07              15:49:00   - 03:55
12   Пт    5.08      04:43:00     20:28:01              15:45:01   - 03:59
13   Сб    6.08      04:44:54     20:25:54              15:41:00   - 04:01
14   Вc    7.08      04:46:48     20:23:46              15:36:58   - 04:02
15   Пн    8.08      04:48:42     20:21:36              15:32:54   - 04:04
16   Вт    9.08      04:50:37     20:19:24              15:28:47   - 04:07
17   Ср   10.08      04:52:32     20:17:11              15:24:39   - 04:08
18   Чт   11.08      04:54:27     20:14:57              15:20:30   - 04:09
19   Пт   12.08      04:56:23     20:12:41              15:16:18   - 04:12
20   Сб   13.08      04:58:18     20:10:24              15:12:06   - 04:12
21   Вc   14.08      05:00:14     20:08:05              15:07:51   - 04:15
22   Пн   15.08      05:02:10     20:05:46              15:03:36   - 04:15
23   Вт   16.08      05:04:06     20:03:25              14:59:19   - 04:17
24   Ср   17.08      05:06:02     20:01:03              14:55:01   - 04:18
25   Чт   18.08      05:07:59     19:58:40              14:50:41   - 04:20
26   Пт   19.08      05:09:55     19:56:16              14:46:21   - 04:20
27   Сб   20.08      05:11:51     19:53:51              14:42:00   - 04:21
28   Вc   21.08      05:13:47     19:51:25              14:37:38   - 04:22
29   Пн   22.08      05:15:44     19:48:59              14:33:15   - 04:23
30   Вт   23.08      05:17:40     19:46:31              14:28:51   - 04:24

In [15]:
# конвертация интервала в timedelta
daylight['Продолжительность дня'] = pd.to_timedelta(daylight['Продолжительность дня'])

In [16]:
# средняя продолжительность светового дня за месяц
daylight['Продолжительность дня'].mean()

Timedelta('0 days 15:31:38.129032258')